version: '3.9'

services:
  db:
    container_name: db_postgres
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}

    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ./scripts/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - postgres

  db_admin:
    container_name: db_admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@dev.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge