"""TusaTable table added, association with User table

Revision ID: 2050d207702d
Revises: 7b6e271a5a0a
Create Date: 2023-08-16 21:22:45.566828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2050d207702d'
down_revision: Union[str, None] = '7b6e271a5a0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tusa_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tusa_table_id'), 'tusa_table', ['id'], unique=False)
    op.create_table('user_tusa_table_association',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tusa_table_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tusa_table_id'], ['tusa_table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'tusa_table_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_tusa_table_association')
    op.drop_index(op.f('ix_tusa_table_id'), table_name='tusa_table')
    op.drop_table('tusa_table')
    # ### end Alembic commands ###
